In [1]:
import scanpy as sc

In [3]:
adata = sc.read_h5ad("../data/raw/pbmc68k_reduced/pbmc68k_reduced.h5ad")
adata

AnnData object with n_obs × n_vars = 700 × 765
    obs: 'bulk_labels', 'n_genes', 'percent_mito', 'n_counts', 'S_score', 'G2M_score', 'phase', 'louvain'
    var: 'n_counts', 'means', 'dispersions', 'dispersions_norm', 'highly_variable'
    uns: 'bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'
    obsm: 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'
    layers: None (.X)

In [4]:
print(adata.X[:5, :5])

print(type(adata.X))

print(adata.raw)

print(adata.layers)

[[-0.326 -0.191 -0.728 -0.301  3.386]
 [ 1.171 -0.191  0.795 -1.2   -0.174]
 [-0.326 -0.191  0.483 -1.2   -0.174]
 [-0.326 -0.191  1.134 -0.157 -0.174]
 [-0.326 -0.191 -0.728 -0.607 -0.174]]
<class 'numpy.ndarray'>
Raw AnnData with n_obs × n_vars = 700 × 765
Layers with keys: None


In [9]:
import numpy as np
from scipy import sparse

raw_x = adata.raw.X

print(type(raw_x))
print("Shape:", raw_x.shape)

# check if matrix is sparse or dense, if dense use numpyarray commands
if sparse.issparse(raw_x):
    values = raw_x.data
else:
    values = np.asarray(raw_x).ravel()

print("Min stored value:", values.min())
print("Max stored value:", values.max())
print("All integer-like:", np.allclose(values, np.round(values)))
print("First 20 nonzero values:", values[:20])

<class 'scipy.sparse._csr.csr_matrix'>
Shape: (700, 765)
Min stored value: 0.719
Max stored value: 6.489
All integer-like: False
First 20 nonzero values: [1.591 1.591 1.591 2.177 2.544 1.591 2.177 1.591 2.812 1.591 1.591 1.591
 2.177 1.591 2.177 2.544 2.544 3.023 1.591 2.177]


In [10]:
adata.uns.keys()

dict_keys(['bulk_labels_colors', 'louvain', 'louvain_colors', 'neighbors', 'pca', 'rank_genes_groups'])

In [14]:
adata.uns["pca"]

{'variance': array([30.928047 , 21.182432 , 14.686322 , 11.570731 ,  9.232856 ,
         7.3497834,  4.338316 ,  3.197439 ,  3.1584399,  2.910167 ,
         2.649945 ,  2.540031 ,  2.4057367,  2.3872852,  2.2644212,
         2.2250588,  2.189688 ,  2.134691 ,  2.0775423,  2.0560663,
         2.007874 ,  1.9969993,  1.9606696,  1.9441428,  1.9129871,
         1.9063067,  1.8529838,  1.8260264,  1.7946786,  1.7489465,
         1.7449841,  1.7298484,  1.70099  ,  1.6571085,  1.6406441,
         1.6235017,  1.6012688,  1.5806534,  1.5531204,  1.5331998,
         1.5166894,  1.4852371,  1.4748584,  1.4530103,  1.4340347,
         1.4083625,  1.375356 ,  1.3701098,  1.356156 ,  1.3449155],
       dtype=float32),
 'variance_ratio': array([0.09770954, 0.06692067, 0.04639781, 0.03655487, 0.02916893,
        0.02321983, 0.01370584, 0.01010152, 0.00997831, 0.00919395,
        0.00837185, 0.0080246 , 0.00760033, 0.00754204, 0.00715388,
        0.00702952, 0.00691778, 0.00674403, 0.00656348, 0.0064

In [15]:
adata.uns["neighbors"]

{'params': {'method': 'umap', 'n_neighbors': array([10])}}

In [16]:
adata.uns["rank_genes_groups"]


{'names': array([('RGS19', 'ITM2A', 'CAPG', 'CCL5', 'CD8B', 'C1QA', 'CD79A', 'PRSS57', 'GNLY', 'CST3'),
        ('HIST1H4C', 'RPL39', 'GABARAPL2', 'GNLY', 'CD8A', 'PSAP', 'CD79B', 'SNHG7', 'NKG7', 'LYZ'),
        ('IL32', 'TIMM10', 'FDX1', 'NKG7', 'RP11-291B21.2', 'COX14', 'MS4A1', 'SERPINB1', 'CD7', 'LST1'),
        ('GSTK1', 'CWC15', 'CRIP1', 'GZMH', 'CD7', 'NEAT1', 'IGJ', 'C19orf77', 'CLIC3', 'IRF7'),
        ('SKP1', 'CXCR4', 'GATA3', 'CHCHD7', 'NECAP2', 'NUP214', 'IGLL5', 'SPINK2', 'SPON2', 'C10orf54'),
        ('TMBIM6', 'LSM5', 'HPCAL1', 'SRSF2', 'ANAPC16', 'RAB7A', 'SPIB', 'IMPDH2', 'TYROBP', 'ZNHIT1'),
        ('CALM3', 'LSMD1', 'DNAJC1', 'ANXA1', 'SAMD3', 'OAS1', 'UBE2J1', 'H2AFY', 'GZMB', 'CD33'),
        ('COPE', 'SUPT4H1', 'C20orf27', 'MRFAP1', 'YWHAB', 'HMGB2', 'SMARCB1', 'EGFL7', 'PLAC8', 'ILK'),
        ('CD3E', 'SRSF7', 'MIEN1', 'DUSP2', 'CARS', 'SLTM', 'MZB1', 'CYTL1', 'FCER1G', 'IL32'),
        ('CAPN2', 'MTDH', 'ACAA1', 'KLRB1', 'HMGA1', 'TMEM176B', 'CCDC50', 'SNHG8

In [17]:
adata.uns["louvain"]

{'params': {'random_state': array([0]), 'resolution': array([1])}}